// ─── Admin English Translations ───

const adminEn: Record<string, string> = {
  'نظرة عامة': 'Overview',
  'المنتجات': 'Products',
  'الطلبات': 'Orders',
  'العملاء': 'Customers',
  'المدفوعات': 'Payments',
  'المحادثات': 'Chats',
  'المدونة': 'Blog',
  'المصادر': 'Sources',
  'التخصيص': 'Customize',
  'الإعلانات': 'Announcements',
  'الإعدادات': 'Settings',
  'لوحة التحكم': 'Dashboard',
  'فلاش بوب أب': 'Flash Popup',
  'إجمالي الطلبات': 'Total Orders',
  'إجمالي العملاء': 'Total Customers',
  'إجمالي الإيرادات': 'Total Revenue',
  'طلبات اليوم': 'Today\'s Orders',
  'إدارة المنتجات': 'Manage Products',
  'إضافة منتج': 'Add Product',
  'إدارة الطلبات': 'Manage Orders',
  'إدارة العملاء': 'Manage Customers',
  'إدارة المدفوعات': 'Manage Payments',
  'بحث': 'Search',
  'تصدير': 'Export',
  'تحديث': 'Refresh',
  'حذف': 'Delete',
  'تعديل': 'Edit',
  'حفظ': 'Save',
  'إلغاء': 'Cancel',
  'تأكيد': 'Confirm',
  'نعم': 'Yes',
  'لا': 'No',
  'فلاتر': 'Filters',
  'الحالة': 'Status',
  'التاريخ': 'Date',
  'المبلغ': 'Amount',
  'الاسم': 'Name',
  'البريد': 'Email',
  'الهاتف': 'Phone',
  'نشط': 'Active',
  'معلق': 'Pending',
  'مكتمل': 'Completed',
  'ملغي': 'Cancelled',
  'فشل': 'Failed',
  'قيد المعالجة': 'Processing',
  'جاري التنفيذ': 'In Progress',
};

export default adminEn;
